"""Scheduled recap generation (7h morning, 13h afternoon).

The recap is sent as three separate Telegram messages to minimize token usage:
1. Agenda — generated by Claude (needs to merge Google + Zimbra).
2. Todos — fetched directly from Supabase, rendered by the bot.
3. Emails — fetched directly from Supabase, rendered by the bot.
"""

from datetime import datetime, timedelta

import pytz
import structlog

from bot.api_client import api_client
from bot.formatting import format_emails_list, format_events_list, format_todos_list
from config import settings

logger = structlog.get_logger(__name__)


async def _build_todos_message() -> str | None:
    try:
        result = await api_client.call("/todos/list", {"filter": "pending"})
    except Exception as e:
        logger.error("recap_todos_fetch_failed", error=str(e))
        return None
    if not result.get("success"):
        return None
    todos = (result.get("data") or {}).get("todos") or []
    return format_todos_list(todos, header="📝 Todos en cours :")


async def _build_emails_message() -> tuple[str | None, list[str]]:
    """Build the emails section and return (text, ids_to_mark_notified)."""
    try:
        result = await api_client.call("/emails/recap", {})
    except Exception as e:
        logger.error("recap_emails_fetch_failed", error=str(e))
        return None, []
    if not result.get("success"):
        return None, []

    data = result.get("data") or {}
    emails = data.get("emails") or []
    extra = int(data.get("extra_count") or 0)

    if not emails and extra == 0:
        return None, []

    header = f"📧 Mails non-lus ({len(emails)}) :" if emails else "📧 Mails non-lus :"
    body = format_emails_list(emails, header=header) if emails else header
    if extra > 0:
        body = f"{body}\n\n(+ {extra} autres mails non-lus des 2 derniers jours)"

    shown_ids = [e["id"] for e in emails if e.get("id")]
    return body, shown_ids


async def _mark_emails_notified(email_ids: list[str]) -> None:
    if not email_ids:
        return
    try:
        await api_client.call("/emails/mark_notified", {"email_ids": email_ids})
    except Exception as e:
        logger.error("recap_mark_notified_failed", error=str(e))


async def _send_to_all_chats(bot, text: str, parse_mode: str | None = None) -> bool:
    """Send a message to every authorized chat. Returns True if at least one delivered."""
    delivered = False
    for chat_id in settings.allowed_chat_ids_list:
        try:
            await bot.send_message(chat_id=chat_id, text=text, parse_mode=parse_mode)
            delivered = True
        except Exception as e:
            logger.error("recap_send_failed", chat_id=chat_id, error=str(e))
    return delivered


async def _build_agenda_message(target_date_str: str, header: str) -> str | None:
    """Fetch events for `target_date_str` and render directly, no Claude.

    Saves a full Claude turn (system + tools + list_events tool result + final
    response) per recap. The format mirrors the SYSTEM_PROMPT convention
    (📚 for Zimbra, 🗓️ for Google).
    """
    try:
        result = await api_client.call("/calendar/list_events", {"target_date": target_date_str})
    except Exception as e:
        logger.error("recap_agenda_fetch_failed", date=target_date_str, error=str(e))
        return None
    if not result.get("success"):
        return None
    events = (result.get("data") or {}).get("events") or []
    return format_events_list(events, header=header)


async def send_recap(bot, recap_type: str) -> None:
    """Generate and send a 3-part recap: agenda, todos, emails."""
    tz = pytz.timezone(settings.timezone)
    now = datetime.now(tz)

    if recap_type == "morning":
        target_date = now.strftime("%Y-%m-%d")
        agenda_header = "📅 Agenda du jour :"
    else:
        target_date = (now + timedelta(days=1)).strftime("%Y-%m-%d")
        agenda_header = "📅 Agenda demain :"

    # 1. Agenda — direct API call, no Claude (saves ~5500 tokens per recap)
    agenda_text = await _build_agenda_message(target_date, agenda_header)
    if agenda_text:
        await _send_to_all_chats(bot, agenda_text)
        logger.info("recap_agenda_sent", type=recap_type)

    # 2. Todos (direct, no Claude)
    todos_text = await _build_todos_message()
    if todos_text:
        await _send_to_all_chats(bot, todos_text)
        logger.info("recap_todos_sent", type=recap_type)

    # 3. Emails (direct, no Claude)
    emails_text, shown_ids = await _build_emails_message()
    if emails_text:
        delivered = await _send_to_all_chats(bot, emails_text)
        if delivered and shown_ids:
            await _mark_emails_notified(shown_ids)
        logger.info("recap_emails_sent", type=recap_type, count=len(shown_ids))
